# Generated by Django 6.0.1 on 2026-02-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número do mundo (1-6)', unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(default='chef', help_text='Nome do ícone (chef, cash-register, chart-line, trophy, etc)', max_length=50)),
                ('cor_primaria', models.CharField(default='#e30613', help_text='Cor hex do mundo', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mundo',
                'verbose_name_plural': 'Mundos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='NotaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(help_text='Nota de 1 (vermelho) a 5 (verde)')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('automatica', models.BooleanField(default=False, help_text='True se gerada automaticamente por inatividade')),
                ('observacao', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_saude', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Nota de Saúde',
                'verbose_name_plural': 'Notas de Saúde',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(help_text='Ordem do step dentro do mundo')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('instrucoes', models.TextField(help_text='Instruções detalhadas para o aluno')),
                ('tipo_validacao', models.CharField(choices=[('FOTO', 'Foto'), ('FORMULARIO', 'Formulário'), ('TEXTO', 'Texto')], default='FOTO', max_length=20)),
                ('pontos', models.IntegerField(default=10, help_text='Pontos ao completar este step')),
                ('ativo', models.BooleanField(default=True)),
                ('mundo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='trilha.mundo')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
                'ordering': ['mundo__numero', 'ordem'],
                'unique_together': {('mundo', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='ProgressoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BLOQUEADO', 'Bloqueado'), ('EM_ANDAMENTO', 'Em Andamento'), ('PENDENTE_VALIDACAO', 'Pendente Validação'), ('CONCLUIDO', 'Concluído')], default='BLOQUEADO', max_length=25)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='usuarios.usuario')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='trilha.step')),
            ],
            options={
                'verbose_name': 'Progresso do Aluno',
                'verbose_name_plural': 'Progressos dos Alunos',
                'unique_together': {('aluno', 'step')},
            },
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, help_text='Arquivo enviado (foto ou documento)', null=True, upload_to='submissoes/%Y/%m/')),
                ('resposta_texto', models.TextField(blank=True, help_text='Resposta em texto')),
                ('resposta_formulario', models.JSONField(blank=True, help_text='Respostas do formulário em JSON', null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('aprovado', models.BooleanField(help_text='null=pendente, True=aprovado, False=reprovado', null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback do monitor')),
                ('progresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='trilha.progressoaluno')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Submissão',
                'verbose_name_plural': 'Submissões',
                'ordering': ['-data_envio'],
            },
        ),
    ]
