# Generated by Django 6.0.1 on 2026-02-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MONITOR', 'Monitor'), ('ALUNO', 'Aluno')], default='ALUNO', max_length=20)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('foto', models.ImageField(blank=True, help_text='Foto de perfil do usuário', null=True, upload_to='fotos_usuarios/')),
                ('telefone', models.CharField(blank=True, help_text='WhatsApp para alertas', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
