# Generated by Django 5.1.4 on 2026-02-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_signup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
